package entity.chatbot;

/**
 * Core interface for AI Client operations.
 * Provides a contract for evaluating and responding to user queries.
 */
public interface AiClient {
    /**
     * Evaluates the given message and generates a response.
     *
     * @param message The user-provided message.
     * @return A response generated by the AI.
     * @throws Exception If an error occurs during processing.
     */
    String evaluateAndRespond(String message) throws Exception;
}
